cifar10:
  mean:
  - 0.491137
  - 0.482111
  - 0.446449
  std:
  - 0.246869
  - 0.24343
  - 0.261603
cifar100:
  mean:
  - 0.507056
  - 0.486423
  - 0.440584
  std:
  - 0.267242
  - 0.256334
  - 0.276031
tiny_imagenet:
  mean:
  - 0.480044
  - 0.44791
  - 0.397422
  std:
  - 0.276342
  - 0.268785
  - 0.281476
